[install]
# Use npm registry for better compatibility with existing npm workflows
registry = "https://registry.npmjs.org/"
# Cache packages for faster installs
cache = true
# Install peer dependencies automatically
peer = true

[install.scopes]
# Configure scoped packages if needed
# "@mycompany": "https://npm.mycompany.com/"

[test]
# Run tests in parallel for faster execution
concurrent = true
# Show detailed test output
verbose = true
# Set test timeout
timeout = 10000

[run]
# Configure how bun run works
# bun = "bun"  # Use bun as the runtime
