name: CI

on:
  push:
    branches: [main, next]

permissions:
  contents: write # <-- allows pushing tags/commits
  issues: write # <-- needed for GitHub release notes
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '--skip-ci')
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Setup Bun latest
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun run types

      - name: Build
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            dist/
            package.json
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    if: >
      !contains(github.event.head_commit.message, '--skip-ci')
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]
        bun-version: [1.0.0, latest]

    steps:
      - name: Checkout code
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        with:
          name: build-files
          path: .

      - name: Install dependencies
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        run: bun install

      - name: Run tests
        if: >
          !contains(github.event.head_commit.message, '--skip-test')
        run: bun test:all

  release:
    needs: test
    runs-on: ubuntu-latest
    if: >
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next') &&
      !contains(github.event.head_commit.message, '--skip-ci')
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # semantic-release requires full history

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-files
          path: .

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
